name: Deploy to Azure

on:
  push:
    branches:
      - 'main'

jobs:
  deploy-to-aci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Pull Docker image from Docker Hub
        run: docker pull ${{ secrets.DOCKER_USERNAME }}/docker_image_tp2:latest

      - name: Login to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Tag Docker image with ACR URI
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/docker_image_tp2:latest ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.ACR_REPO_NAME }}/docker_image_tp2:latest

      - name: Push Docker image to Azure Container Registry (ACR)
        run: docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.ACR_REPO_NAME }}/docker_image_tp2:latest

      - name: Deploy to Azure Container Instances (ACI)
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: devops-<20231169>
          image-name: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.ACR_REPO_NAME }}/docker_image_tp2:latest
          container-name: 20231169
          location: francecentral
          ports: 80
