name: Deploy to Azure

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Tp3_devops/**'
      - '.github/workflows/deploy_azure.yml'

jobs:
  deploy-to-aci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Lint Dockerfile with hadolint
        uses:  hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Tp3_devops/Dockerfile
          failure-threshold: error

      - name: Login to Azure Container Registry (ACR)
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and tag Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Tp3_devops
          file: ./Tp3_devops/Dockerfile
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.ID_EFREI }}:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Instances (ACI)
        uses: azure/aci-deploy@v1
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          dns-name-label: devops-${{ secrets.ID_EFREI }}
          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/${{ secrets.ID_EFREI }}:latest
          name: ${{ secrets.ID_EFREI }}
          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          environment-variables: OPENWEATHER_API_KEY=${{ secrets.OPENWEATHER_API_KEY }}
          location: germanywestcentral
          #ports: 80
