name: Docker Build and Publish

on:
  push:
    branches:
      - 'main'
    paths:
      - 'Tp2_devops/**'
      - '.github/workflows/main.yml'
jobs:
  lint_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Lint Dockerfile with hadolint
        uses:  hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Tp2_devops/Dockerfile
          fail-on: error

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./Tp2_devops
          file: ./Tp2_devops/Dockerfile
          push: true
          tags: limaoscargolf/docker_image_tp2:latest
